# Assignment 7: NumPy

## Q1 NumPy Basics


**What is NumPy and its advantages over regular Python lists?**  
NumPy is a powerful Python library used for numerical and scientific computing. It provides support for arrays, matrices, and a large number of mathematical functions.

**Advantages over Python lists:**  
- Faster execution due to optimized C-based backend  
- Less memory consumption  
- Convenient array slicing and broadcasting  
- Built-in mathematical, logical, and statistical operations


In [8]:

import numpy as np

# Creating a NumPy array from a list
numbers = [1, 2, 3, 4, 5]
np_array = np.array(numbers)

# Performing basic arithmetic operations
added_array = np_array + 5
multiplied_array = np_array * 2

print("Original:", np_array)
print("Added:", added_array)
print("Multiplied:", multiplied_array)


Original: [1 2 3 4 5]
Added: [ 6  7  8  9 10]
Multiplied: [ 2  4  6  8 10]


## Q2 Special Arrays


**Creating different types of arrays in NumPy:**  
- `np.zeros(shape)` creates an array filled with zeros.  
- `np.ones(shape)` creates an array filled with ones.  
- `np.random.randint(low, high, size)` creates an array with random integers in a specified range.


In [9]:

import numpy as np

zeros_array = np.zeros((3, 3))
ones_array = np.ones((3, 3))
random_array = np.random.randint(1, 11, (3, 3))

print("Zeros:\n", zeros_array)
print("Ones:\n", ones_array)
print("Random Integers:\n", random_array)


Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Random Integers:
 [[ 7  2  4]
 [ 2  2 10]
 [ 7  3  5]]


## Q3 Indexing Slicing


**Array indexing and slicing in NumPy:**  
- Similar to lists, but more powerful with multi-dimensional support.  
- You can slice 2D arrays using syntax like `array[row_start:row_end, col_start:col_end]`.  
- Faster and more efficient than standard Python list slicing.


In [10]:

import numpy as np

array_2d = np.arange(16).reshape((4, 4))
subarray = array_2d[1:3, 1:3]

print("Original 4x4 Array:\n", array_2d)
print("2x2 Subarray:\n", subarray)


Original 4x4 Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
2x2 Subarray:
 [[ 5  6]
 [ 9 10]]


## Q4 Statistics


**Common statistical functions in NumPy:**  
- `np.mean()` computes the average of array elements.  
- `np.median()` computes the middle value.  
- `np.std()` computes the standard deviation.  
These help in analyzing numerical data efficiently.


In [11]:

import numpy as np

data = np.random.rand(100)
mean = np.mean(data)
median = np.median(data)
std_dev = np.std(data)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)


Mean: 0.4676611423797483
Median: 0.4373226733881726
Standard Deviation: 0.28725418709994044


## Q5 Operations


**Element-wise and matrix operations in NumPy:**  
- Element-wise operations: Operations done on each corresponding element (e.g., `a + b`).  
- Matrix operations: Use functions like `np.dot()` or `@` for matrix multiplication.


In [12]:

import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

elementwise_add = a + b
elementwise_sub = a - b
matrix_mul = np.dot(a, b)

print("Addition:\n", elementwise_add)
print("Subtraction:\n", elementwise_sub)
print("Matrix Multiplication:\n", matrix_mul)


Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Matrix Multiplication:
 [[19 22]
 [43 50]]


## Q6 Broadcasting


**Broadcasting in NumPy:**  
Broadcasting allows NumPy to perform operations on arrays of different shapes without explicit replication.  
E.g., adding a 1D array to a 2D array row-wise.


In [13]:

import numpy as np

array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_1d = np.array([10, 20, 30])

broadcasted_sum = array_2d + array_1d

print("Broadcasted Result:\n", broadcasted_sum)


Broadcasted Result:
 [[11 22 33]
 [14 25 36]]


## Q7 Handle NaN


**Handling NaN (Not a Number) values in NumPy:**  
- `np.isnan(array)` returns boolean array for NaNs.  
- `np.nanmean(array)` computes mean ignoring NaNs.  
- `np.where(condition, x, y)` can be used to replace NaNs.


In [14]:

import numpy as np

array_with_nan = np.array([1, 2, np.nan, 4, 5, np.nan])
mean_value = np.nanmean(array_with_nan)
filled_array = np.where(np.isnan(array_with_nan), mean_value, array_with_nan)

print("Original:", array_with_nan)
print("Mean:", mean_value)
print("Filled:", filled_array)


Original: [ 1.  2. nan  4.  5. nan]
Mean: 3.0
Filled: [1. 2. 3. 4. 5. 3.]


## Q8 Reshape Flatten


**reshape() and flatten():**  
- `reshape()` changes the shape of an array without changing its data.  
- `flatten()` converts a multi-dimensional array into a 1D array.


In [15]:

import numpy as np

original_array = np.arange(12)
reshaped_array = original_array.reshape((3, 4))
flattened_array = reshaped_array.flatten()

print("Original:", original_array)
print("Reshaped:", reshaped_array)
print("Flattened:", flattened_array)


Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]


## Q9 Linear Algebra


**`numpy.linalg` for linear algebra:**  
- `np.linalg.inv()` computes the inverse of a matrix.  
- `np.linalg.eig()` computes eigenvalues and eigenvectors.  
Used in systems of equations, ML, and more.


In [16]:

import numpy as np

matrix = np.array([[4, 7], [2, 6]])
inverse_matrix = np.linalg.inv(matrix)
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Matrix:", matrix)
print("Inverse:", inverse_matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)


Matrix: [[4 7]
 [2 6]]
Inverse: [[ 0.6 -0.7]
 [-0.2  0.4]]
Eigenvalues: [1.12701665 8.87298335]
Eigenvectors: [[-0.92511345 -0.82071729]
 [ 0.37969079 -0.57133452]]


## Q10 Save Load


**Saving and loading NumPy arrays:**  
- `np.save('filename.npy', array)` saves the array in binary `.npy` format.  
- `np.load('filename.npy')` loads the saved array.  
Efficient for data persistence.


In [17]:

import numpy as np

array_to_save = np.array([1, 2, 3, 4, 5])
np.save('saved_array.npy', array_to_save)

loaded_array = np.load('saved_array.npy')
print("Loaded Array:", loaded_array)


Loaded Array: [1 2 3 4 5]
